---
apiVersion: apps/v1
kind: Deployment
metadata: 
    name: aks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: app
  template:
    metadata:
      labels:
        name: app
    spec:
      containers:  
        - name: apps
          image: https://hub.docker.com/repository/docker/vishal18doc/vishalnew18
