apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: react
          image: vishal18doc/back:11
          env:
            - name: MONGO_ADDRESS
              value: "10.0.153.228"
#          volumeMounts:
 #           - mountPath: /node
  #            name: pvc
   #   volumes:
    #    - name: pvc
     #     persistentVolumeClaim:
      #      claimName: pvc


