apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /files
    type: DirectoryOrCreate
